#!/bin/bash
# DO NOT EDIT THIS FILE

environment=good

OPAM_LOCATION="$(command -v opam)"
if [[ "$OPAM_LOCATION" == "" ]]; then
  echo "OPAM is NOT available.  This is bad."
  environment=bad
else
  echo "OPAM is available.  Good."
fi

OCAMLC_VERSION="$(ocamlc --version 2>&1)"
if [[ "$OCAMLC_VERSION" == "4.03.0" ]]; then
  echo "OCaml compiler version 4.03.0 is active.  Good."
else
  echo "OCaml compiler version 4.03.0 is NOT active.  This is bad."
  environment=bad
fi

OUNIT_VERSION="$(opam info ounit -f installed-version 2>&1)"
if [[ "$OUNIT_VERSION" =~ "2.0.0" && "$OUNIT_VERSION" =~ "4.03.0" ]]; then
  echo "OUnit version 2.0.0 is active.  Good."
else
  echo "OUnit version 2.0.0 is NOT active.  This is bad."
  environment=bad
fi

YOJSON_VERSION="$(opam info yojson -f installed-version 2>&1)"
if [[ "$YOJSON_VERSION" =~ "1.3.2" && "$YOJSON_VERSION" =~ "4.03.0" ]]; then
  echo "Yojson version 1.3.2 is active.  Good."
else
  echo "Yojson version 1.3.2 is NOT active.  This is bad."
  environment=bad
fi

LAMBDATERM_VERSION="$(opam info ansiterminal -f installed-version 2>&1)"
if [[ "$LAMBDATERM_VERSION" =~ "0.7" && "$LAMBDATERM_VERSION" =~ "4.03.0" ]]; then
  echo "Lambda Term version 0.7 is active.  Good."
else 
  echo "Lambda Term version 0.7 is NOT active.  This is bad."
  environment=bad
fi

if [[ "$environment" == good ]]; then
  cat <<EOF
===========================================================
Your OCaml environment looks good to me.  Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Your OCaml environment looks broken to me. Talk to Sitar.
===========================================================
EOF
fi