(lang dune 3.1)
(name powdershell)
(generate_opam_files true)

(package
 (name powdershell)
 (maintainers dev.null@gmail.com)
 (synopsis "A package to install dev dependencies")
 (depends
  (ocaml
   (= 5.1.1))
  (ounit2
   (= 2.2.7))
  (yojson
   (= 2.1.2))
  (lambda-term
   (= 3.3.2))))
