(lang dune 1.11)
(name powdershell)
(generate_opam_files true)

(package
 (name powdershell)
 (synopsis "A package to install dev dependencies")
 (depends
  (ocaml
   (= 4.08))
  (ounit
   (= 2.2.7))
  (yojson
   (= 2.1.2))
  (lambda-term
   (= 3.3.2))))
